name: "actions-feishu"
description: "Send message to FeiShu via Github Actions"
author: "xiachufang"
inputs:
  webhook:
    description: "Webhook address"
    required: true
  title:
    description: "Message title"
    required: false
    default: "Actions Feishu"
  content:
    description: "Message body"
    required: true
  message_type:
    description: "Message type"
    required: false
    default: "post"
  msg_template_path:
    description: "Path of message template, use it value when message_type is 'template'"
    required: false
    default: "./github/feishu_msg_tmpl/example.json"
  msg_template_values:
    description: "A JSON String for fill out template, use it value when message_type is 'template'"
    required: false
    default: "{}"

outputs:
  response:
    description: "response from Feishu"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: bell
  color: green
